### ISSUE TITLE
FYI: I've included this repo as a submodule

### ISSUE THREAD

**Issue by hooliowobbits** [theranger/zabbix-apt#2]
Hey, nice work, 

thanks for your efforts and for publishing it; much appreciated.

I'm deploying agents for zabbix 3.4.4 using ansible using https://github.com/hooliowobbits/zabbix-push, and i've included this repo as a submodule.  I could have forked, but i thought why bother, what you have works.  so thanks again :)

Kind regards, Hoolio

**Comment by theranger** [comment]
Thanks!
