### ISSUE TITLE
Zabbix-agent 3.4 is not longer accepting the newline

### ISSUE THREAD

**Issue by denisgolius** [theranger/zabbix-apt#3]
For zabbix-agent 3.4 is not longer accepting the newline which will be given by the commands in apt.conf. Just add |perl -pe 'chomp if eof' to the end of all parameter lines, to get it back working.

**Comment by theranger** [comment]
Latest commit already fixes that:

```
UserParameter=apt.security,apt-get -s upgrade | grep -ci ^inst.*security | tr -d '\n'
UserParameter=apt.updates,apt-get -s upgrade | grep -iPc '^Inst((?!security).)*$' | tr -d '\n'
```

Firing up Perl interpreter on every poll for just removing a newline is not optimal suggestion.

**Comment by denisgolius** [comment]
hm... I didn't look at this commit :) Thnx
