### ISSUE TITLE
Config for Zabbix 3.4.8

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [theranger/zabbix-apt#4]
I read the comments from the Zabbix share https://share.zabbix.com/cat-app/app-other/apt-updates-monitoring

Apparently putting `|perl -pe 'chomp if eof'` in the apt config file will fix the issue.

@theranger Do you know if this plugin already works for 3.4? OR do we need to do the workaround?

**Comment by theranger** [comment]
This has already been discussed here multiple times. As mentioned before, latest commit already fixes this issue:

https://github.com/theranger/zabbix-apt/commit/6371cc9b6584417dc46e3341fc5d5379707c4a40
